from typing import Callable, Generator
# Exercise 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with  and , the first  terms will be: 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# First we create fibonacci sequance generator:
def fibonacci(max_value: int) -> Generator:
    # max_value - that is the number which we want to validate each next fibonacci sequance number against (like in the task: 4 000 000)

    # starting number of fibonnaci seq.
    start = 1
    # variable for storing previous element of the sequance
    prev_element = 1
    # prev - intermediate step to store start's value BEFORE we add prev_element to it.
    # if there were no prev variable and only prev_element,
    # then we would add 1 to prev_variable (1+1 = 2) and then add that to start (2 + 1 ) = 3, which is obviously wrong logic
    prev = 0
    # while loop to enable generator features (will be stopped on reaching our max_value)
    while True:
        # immediately return first fibonacci element
        yield start
        # storing previous element in a variable
        prev = start
        # incrementing by prev_element (which at the start is the same as variable start)
        start += prev_element
        # checking if the start variable has reached the limit: yes -> break the while loop, no -> continue
        if start >= max_value:
            break
        # updating prev_element using prev variable
        prev_element = prev

# Creating method to accept the ceiling from the user (4_000_000) and create generator and then return sum of all even elements of that sequence
def fib_even_elements(ceiling: int, provider: Callable) -> int:
    # I will use list comprehension, since it is much easier, but i will also provide alternative method with manual even check)
    return sum([num for num in provider(ceiling) if num % 2 == 0])

def fib_even_elements_extd(ceiling: int, provider: Callable) -> int:
    # create generator 
    fib_gen = provider(ceiling)
    sum = 0

    for el in fib_gen:
        if el % 2 == 0:
            sum += el

